config/routes.rb
CaritasMain::Application.routes.draw do

  root :to => 'mains#index'
  
  scope :controller => :mains do
    get 'about'

    match "our_projects/caritas" => "mains#caritas"

  end
    
  #CONTACT FORM
  match 'contact' => 'contact#new', :as => 'contact', :via => :get   
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  
end

app/models/message.rb
class Message 
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :company, :number, :body

  #validates :name, :email, :company, :number, :body, :presence => true
  #validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def new
    @title = 'Contact Us'
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end 
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

def index

end

def about

end

def supported_living

end


#Our Projects
def caritas
 render 'mains/our_projects/caritas'

end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
  	base_title = "Merthyr Tydfil Supported Housing Services"
  		if page_title.empty?
  			base_title
  		else
  			"#{base_title} | #{page_title}"
  		end
	end


end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/contact/new.html.erb
<% provide(:title, 'Contact Us') %>
<div class="wrap_headline">
 <div class="headline">
  <h1>Contact Us</h1>
 </div>
</div>
			
<div class="container">			
 <section id="middle">
  <div class="middle_inner">


	<div class="content_wrap">
	 <section id="content">
	  <div class="entry">
	   <div class="resizable_block">
		<div id="map_canvas" class="google_map fullwidth"></div>
	   </div>
									
	<div class="cmsms-form-builder">
    <div class="one_half">
		<%= form_for @message, :url => contact_path, :method => :post, :html => {:id => 'contactform' } do |f| %> 
      
          <div class="control-group">
           <%= f.label :name, 'Name', :class => 'control-label' %>
            <div class="controls">
             <%= f.text_field :name, :id => 'inputName', :class => 'name', :placeholder => 'Enter Name Here...' %>
             <span class="help-inline" style="display: none;">Please Enter Your Name</span>
            </div>
          </div>

          <div class="control-group">
         <%= f.label :email, 'Email Address', :class => 'control-label' %>
         <div class="controls">
         <%= f.text_field :email, :id => 'inputEmail', :class => 'email', :placeholder => 'Enter Your E-mail Address...' %>
         <span class="help-inline" style="display: none;">Please Check Your Email</span>
         </div>
        </div>

           <div class="control-group">
         <%= f.label :number, 'Telephone Number', :class => 'control-label' %>
         <div class="controls">
         <%= f.text_field :number, :id => 'inputTel', :class => 'phone', :placeholder => 'Enter Your Telephone Number' %>
         <span class="help-inline" style="display: none;">Please Check Your Phone Number</span>
         </div>
        </div>

         <div class="control-group">
         <%= f.label :company, 'Company Name', :class => 'control-label' %>
         <div class="controls">
         <%= f.text_field :company, :id => 'inputCompany', :class => 'phone', :placeholder => 'If applicable' %>
         <span class="help-inline" style="display: none;">Please Check Your Company Name</span>
         </div>
        </div>

          </div>

          <div class="one_half">
       
          <div class="control-group">   
         <%= f.label :body, 'Your Message', :class => 'control-label' %>
         <div class="controls">
         <%= f.text_area :body, :id => 'textarea' %>
         <span class="help-inline" style="display: none;">Please Enter a Message</span>
         </div>
        </div>

         
       
       
              <div class="control-group">
                <div id="formSubmit">
              <%= f.submit "SEND", :class => 'button', :id => 'validForm' %>
                </div>
              </div>
           
       
      <% end %>
	 
										</div>
									
									</div>
								</div>
							</section>	
				
							<section id="sidebar">
								<div class="one_first">
									<aside class="widget widget_custom_advertising_entries">
										<h2>Address</h2>
										<ul>
											<li class="add">Dan y Garreg</li>
											<li class="add">Upper High Street</li>
											<li class="add">Cefn Coed</li>
											<li class="add">Merthyr Tydfil</li>
											<li class="add">CF48 2HW</li>
											<li class="add">01685 551629</li>
										</ul>
									</aside>	
								</div>


							</section>


						</div>
					</div>
				</section>


<script type="text/javascript">
    window.onload = function () {
        initialize();
    }
</script>
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApUO4ajt4kh5KnLE-zJbdmDKrVf7zqsvA&sensor=false">
    </script>

 <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(51.764856, -3.409472),
          zoom: 13,
          scrollwheel: false,
          draggable: false,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        var map = new google.maps.Map(document.getElementById("map_canvas"),
            mapOptions);

        var marker = new google.maps.Marker({
          position: map.getCenter(),
          map: map,
          title: 'Caritas'
        });

        var center;
        function calculateCenter() {
         center = map.getCenter();
        }
         google.maps.event.addDomListener(map, 'idle', function() {
         calculateCenter();
        });
         google.maps.event.addDomListener(window, 'resize', function() {
         map.setCenter(center);
        });

      }


      /* Submit button Disabled until Validation */

  jQuery(document).ready(function() {
    validate();
    jQuery('#inputName, #inputEmail, #inputTel' ).change(validate);
  });

  function validate(){
      if (jQuery('#inputName').val().length   >   0   &&
          jQuery('#inputEmail').val().length  >   0   &&
          jQuery('#inputTel').val().length    >   0) {
          jQuery("input[type=submit]").prop("disabled", false);
      }
      else {
        jQuery("input[type=submit]").prop("disabled", true);
      }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="description" content="We support individuals which may have a Learning Disability, Fragile X, Autism Spectrum Disorder, Challenging Behaviour, Asperger’s Syndrome, Physical Disability, Sensory Impairment and/or a Mental Health Issue, (dual diagnosis)." />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title><%= full_title(yield(:title)) %></title>

  <!-- Google Analytics -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44913136-1', 'supportedlivingmerthyr.co.uk');
  ga('send', 'pageview');
</script>

  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" type="text/css" />
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oxygen:400,300,700" type="text/css" />
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Headland+One" type="text/css" />
	
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- Favicon -->
  <%= favicon_link_tag 'favicon.ico' %>

  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>

</head>
<body>
 <section id="page">
  <a href="#" id="slide_top">
    <span id="slide_top_hover"></span>
  </a>
 	<%= render 'shared/header' %>
 	 <div class="container">
 	  <%= yield %>
     </div>
 </section>
    <%= render 'shared/footer' %>



</body>
</html>

app/views/mains/about.html.erb
<% provide(:title, 'About Supported Living Merthyr Tydfil') %>
<div class="wrap_headline">
 <div class="headline">
  <h1>About Us</h1>
 </div>
</div>


<div class="container">			
 <section id="middle">
  <div class="middle_inner">
   <div class="content_wrap">

	 <div class="entry">
	  <div class="alignleft one_half" style="padding:0;">
		<figure>
			<%= image_tag('/assets/edithhouse/fronthouse.jpg', :class => 'fullwidth') %>
		</figure>
	  </div>
		
		 <p class="bold">SUPPORTED LIVING - PERSON-CENTRED PLANNING</p>

		 <p>We support individuals which may have a Learning Disability, Fragile X, Autism Spectrum Disorder, Challenging Behaviour, Asperger’s Syndrome, Physical Disability, Sensory Impairment and/or a Mental Health Issue, (dual diagnosis).</p>

		 <p>We help them to live the life they want, in the way they want. We work in partnership with individuals to increase their independence, improve their self-care skills, and encourage development of their home and community interests, hobbies and activities, promoting social inclusion.</p>

		 <p>The tenant recieves the support and assistance they need to live in their own home or a home of their own choice. If the Tenant's circumstances change, the support they recieve is changed. The most significant thing is that the support package matches the person’s assessed needs. Service provision is ‘needs led’ and not ‘service led’.</p>

		 <p>Our project can assist with all aspects of daily living; we work with agencies, whose role is to arrange, provide, or commission whatever assistance is necessary for a person to live in a decent and secure home of their own.</p>

		 <p>We help vulnerable indivuduals to stay safe, live happy, healthy and a productive lifestyle in the way that they wish.</p>

		 <p>Supported Living is an innovative approach to housing and support for vulnerable people based on the fundamental belief that every person has a right to lead their own life, to determine where, how, with whom they live and who provides them with support. We endorse this with the development of a Person-Centred Plan.</p>



		 <p>The ‘Person-Centred Plan' includes:</p>


		 <ul>
		  <li>Identifying need and Improve Life Skills.</li>
		  <li>Budget planning, Menu planning.</li>
		  <li>Welfare Benefit - Financial Support.</li>
		  <li>Further Education, Voluntary Work, and Paid Employment if applicable.</li>
		  <li>Accessing Community, Leisure and Sporting activities.</li>
		  <li>Improve Social Networks, promote Social Inclusion.</li>
		  <li>Maintain links with family, friends, interests, religion, other.</li>
		 </ul>


		 <p class="bold">Supported Living Services</p>

         <p>Our Supported Living Service provides a broad range of support to adults 18 to 65.</p>

         <p>We focus on 'Individual-Based Outcomes', to allow service-user’s to grow and develop, such as;</p>

         <ul>
          <li>Promoting Dignity.</li>
          <li>Encourage Choice and Control over Decision Making.</li>
          <li>Advocate Emotional and Physical Health Monitoring.</li>
          <li>Feeling Valued as an Integral part of Society.</li>
          <li>Making a Positive Contribution to the Local Community.</li>
          <li>Life free from Discrimination and Harassment.</li>
          <li>Enable Financial Security and Planning.</li>
          <li>Own accommodation.</li>
          <li>Maintaining relationships....</li>
          <li>Emotional Support.</li>
          <li>Confidence building.</li>
         </ul>

		 
		<div class="cl"></div>
									
		<div class="divider"></div>
		 <h2>Mission Statement</h2><br /> 
			 <div class="ovh">	
			 <blockquote> 
			   <p class="italic">Merthyr Tydfil Supported Housing will provide the highest level of care and support services to our tenants, by working closely with them, their families, health and social service team, other agencies, to promote choice and independence working in a person-centred way.</p>
          </blockquote>
			 </div>												
			<div class="divider"></div>
			 <div class="tour_content">
			  <h2>Why Choose Us</h2><br />
				<ul class="tour">
				 <li class="current">
				  <a href="#">Specialist Services</a>
				 </li>
				 
				 <li>
				  <a href="#">Person-Centered Planning</a>
				 </li>
				
				 <li>
				  <a href="#">Specialist Support Services</a>
				 </li>
				 
				 <li>
				  <a href="#">Supported Living</a>
				 </li>
				 
				 <li>
				  <a href="#">Support Services</a>
				 </li>
				</ul>
				

				<div class="tour_box" style="display:block;">
				 <div class="tour_box_inner">
				  <h5>Specialist Services</h5>
				   <p>Caritas, (Edith Mary House), in association with PartnerShip Share ‘Merthyr’ Limited, a Domiciliary Support Provider, has experience of delivering services to individuals with a wide range of complex care and support needs.</p>

				   <p>With our affiliation with PartnerShip Share 'Merthyr' Limited we are committed to improving the physical and emotional health & wellbeing of the people we support. Our work is, ‘Person-Centred' with the individuals at the centre of all decisions about their future plans.</p>

				 </div>
				</div>
				
				<div class="tour_box">
				 <div class="tour_box_inner">
				  <h5>Person-Centered Planning - PCP</h5>
				   <p>Person Centred Planning is a way of assisting people to work out what they want, the support they require, and helping them get it. It is a working tool for effective planning.</p>

				   <p>All of our services encourage the development of practical and social skills, enabling individuals to progress towards greater independence, at a pace that suits them, ensuring the person is at the centre of the planning process and is carried out in alliance with friends and family.</p>

				   <p>The P.C.P is always focused on getting 'real lives for people and plays a particularly important role in delivering objectives in the, “Valuing People Now” document.</p>

				   <p>The plan we follow is known as MAPS.</p>

				 </div>
				</div>
										
				<div class="tour_box">
				 <div class="tour_box_inner">
				  <h5>Specialist Support Services</h5>
				   <p>We are experienced in providing flexible, bespoke care and support services, tailored to meet the individual needs of clients. We work with Specialist Domiciliary Support Providers, Primary Care Trusts; Secondary Care Trusts, Social Services, DWP, Education; we work within a Multi-Disciplinary Care Framework to deliver bespoke, quality care services.</p>

				   <p>We have proven experience of providing care and support to clients with a variety of complex or specialist care needs and succeed where other traditional supports services fail.</p>

				   <p>Our support workers are trained in;</p>

				   <p class="bold">British Sign Language</p>

				   <p class="bold">PECS</p>

				   <p class="bold">Makaton</p>
				   
				 </div>
				</div>
										
				<div class="tour_box">
				 <div class="tour_box_inner">
				  <h5>Supported Living</h5>
				  <p>We recognise the importance to service-user’s of remaining in a familiar area as they begin to lead a more independent life.  If they know how to get to their friends’ house, how to see their family and the area is recognisable the more likely they will be to do things like shop, socialise, and use the facilities on their own.</p>

				  <p>Proximity to those closest to them, connections to their local community, and knowledge of services can make or break a placement.</p>

				  <p>Individuals with a range of complex needs can be very independent in environments they’re familiar with.</p>

				  <p>Our project focus’s on individual based outcomes, to allow individuals to grow and develop. Outcomes can focus on things like:</p>

				  <ul>
				    <li>Good quality housing and support</li>
         	        <li>Meeting new people - making friends and forming solid relationships</li>
         	        <li>Getting out and about/social inclusion</li>
         	        <li>Take an active role in the community</li>
         	        <li>Being safe/feeling secure</li>
         	        <li>Having a means to communicate and being communicated with</li>
         	        <li>Respect and trust</li>
         	        <li>Staying healthy</li>
         	        <li>Learning new skills</li>
			      </ul>

			      <p>Social inclusion and feeling a part of their local community is the key to so many supported living projects being successful.</p>
				 </div>
				</div>
										
				<div class="tour_box">
				 <div class="tour_box_inner">
				  <h5>Support Services</h5>
					<p>Many adults with special needs are unable to access the support or services they need, which leaves them isolated and vulnerable. A lack of timely appropriate support can result in deterioration in their physical, mental and emotional health. The right support at the right time can have a significant, positive impact upon an individual's quality of life and outcomes.</p>


					<p>Each Person with a Learning Disability is a unique individual, with individual needs.</p>

					<p>All assessments involve the individual, their family or carer, current care provider, (if appropriate) and their social worker or care manager to ensure that the needs of the individual can be met within our service.</p>

					<p>Our specialist supported living project enables vulnerable individuals, with complex needs, to live in their own homes and achieve their own personal goals and aspirations. We want to ensure that vulnerable individuals live as independently as possible, enjoy a fulfilled life, and that their needs are met in their local community.</p>
				 </div>
				</div>
			</div>



			<div class="divider"></div>
			<h2>Frequently Asked Questions</h2><br />

			<p class="clickQuestion">What is Supported Living?</p>
			<div class="reveal-answer">
             <p>Supported living is a way of providing housing and support services to help vulnerable members of our society to lead independent and fulfilling lives. Each person receives a package of support based on their individual needs. The term 'supported living' is flexible and open to interpretation; there's are many type's and models of supported living accommodation – it depends on what works for each person.</p>

             <p>Our project offers;</p>

             <ul>
              <li>Project support at (edith mary house), where support is provided in-line with your assessment.</li>
              <li>Support for compliance with the terms and conditions stated in your Assured Short-Hold Tenancy agreement.</li>
              <li>Independent bedsits that are part of a supported living ‘move-on’ scheme.(this is not provided as an alternative to an external package of care) </li>
             </ul>

			</div><!--/reveal-answer-->

			<p class="clickQuestion">What is an Assured Short hold Tenancy Agreement?</p>
			<div class="reveal-answer">
             <p>An assured short hold tenancy is a tenancy that gives you a legal right to live in your accommodation for an agreed period of time. Your tenancy might be for a set period such as six months - this is known as a fixed-term tenancy. Or it might roll on a week-to-week or month-to-month basis. This is known as a periodic tenancy.</p>

             <p>The law gives you rights to:</p>
             <ul>
             	<li>get information about your tenancy</li>
             	<li>control your home so that you can stop other people from freely entering</li>
             </ul>
           

             	<p>Supported living housing aims to increase each person's independence over time, by gradually reducing the amount of support needed, over a period of time until moving to more independent accomodation.</p>

			</div>



		   </div>
	
<!-- __________________________________________________ Finish Content -->		

<!-- __________________________________________________ Start Sidebar -->
				
							
<!-- __________________________________________________ Finish Sidebar -->	
						</div>
					</div>
				</section>
<!-- __________________________________________________ Finish Middle -->

app/views/mains/our_projects/caritas.html.erb
<% provide(:title, 'Caritas') %>
<div class="wrap_headline">
 <div class="headline">
  <h1>Caritas - Edith Mary House</h1>
 </div>
</div>
			
			
<div class="container">			
 <section id="middle">
  <div class="middle_inner">
   <div class="content_wrap">
	<div class="entry">
	 <div class="align_left one_half">

	  <div class="edith-gallery">
      <div class="slideButtons">
        <span class="prev"></span>
        <span class="next"></span>
    </div>
      <ul class="gallery">
        <li><%= image_tag('/assets/edithhouse/outside2.png', :class => 'fullwidth') %></li>
        <li><%= image_tag('/assets/edithhouse/outside3.jpg', :class => 'fullwidth') %></li>
        <li><%= image_tag('/assets/edithhouse/outside4.jpg', :class => 'fullwidth') %></li>

	  	 
        <li><%= image_tag('/assets/edithhouse/outside.jpg', :class => 'fullwidth') %></li>
        
      

        <li><%= image_tag('/assets/edithhouse/bathroom.jpg', :class => 'fullwidth') %></li>
        <li><%= image_tag('/assets/edithhouse/bathroom1.jpg', :class => 'fullwidth') %></li>
        <li><%= image_tag('/assets/edithhouse/bathroom2.jpg', :class => 'fullwidth') %></li>
        

        <li><%= image_tag('/assets/edithhouse/stairs.jpg', :class => 'fullwidth') %></li>
        <li><%= image_tag('/assets/edithhouse/stairs2.jpg', :class => 'fullwidth') %></li>
        <li><%= image_tag('/assets/edithhouse/bedroom3.jpg', :class => 'fullwidth') %></li>
        <li><%= image_tag('/assets/edithhouse/bedroom4.jpg', :class => 'fullwidth') %></li>
        <li><%= image_tag('/assets/edithhouse/bedroom5.jpg', :class => 'fullwidth') %></li>
      </ul>
      <p class="center italic">Click arrows to cycle through images of the house</p>
    </div>


	 </div>

    <p class="bold">A 'Not-For-Profit' Service offering;</p>
    <p class="bold">Specialist Supported Living Accommodation</p>

    <p class="bold">The Company was set up to respond to and meet the care and support needs of service-users, in Merthyr Tydfil.</p>
	
	 <p>Edith Mary House is a spacious, modern property, within the much sought after area of Cefn Coed in Merthyr Tydfil, (also known locally as Cefn Coed-y-cymmer). It is a small community on the north-western edge of Merthyr Tydfil County Borough in South Wales. It is situated in the neck of land between the rivers Taf Fawr and Taf Fechan. The village lies within the community of Vaynor. Immediately to the north of the village is the hill of Cefn Cil Sanws on the southern slopes of which is Merthyr Tydfil Golf Club. The village is bounded both to the north and the west by the Brecon Beacons National Park.</p>

   <p>Notable features of the village are the A465 Heads of the Valleys Road and the impressive curving Cefn Coed Viaduct, an 1866 Grade II* listed building which formerly carried the Brecon and Merthyr railway over the River Taff but which now carries the Taff Trail, route 8 of the National Cycleway. It is the third largest viaduct in Wales and was designed by engineers Alexander Sutherland and Henry Conybeare. Sutherland was a friend of Robert Thompson Crawshay of the nearby Cyfarthfa Ironworks, and the viaduct was built on a curve to satisfy conditions laid down by the Crawshay Estate.</p>

  <p>The house has a modern kitchen, a large range style cooker with extractor hood, splash back tiling, ceramic tiled flooring, a large fully functioning wet room with shower/dressing area, and a laundry room leading out to a large garden.</p>

  <p>The front of the property has a very large downstairs bedroom, a sensory ‘hide-out’, computer and sitting area, a communal lounge/dining area with large fronted window, sky television, feature fireplace, plastered walls, textured and cove ceiling, wooden laminate flooring, neutral colour scheme, the front window has uninterrupted views across the valley.</p>

  <p>Upstairs comprises of six large bedrooms, (some en-suite) a stunning modern bathroom with Jacuzzi bath and shower, a quiet reading and music area,  and a sensory room complete with a water bed, fibre optic lighting, light and bubble towers and sensory equipment. The room is a therapeutic environment using best practice of care and design making it instrumental in maintaining a person’s physical, cognitive and emotional well-being.</p>

  <p>Using the concepts and research behind 'Snoezelen' in our sensory room, we have created a safe and relaxing environment to suit the needs of the home and our tenants.</p>

  <p class="bold">New in 2014</p>

  <p>In April 2014 the front and back gardens will be sensitively landscaped exposing a sensory garden with intimate spaces where individuals can be immersed in the scents, textures and colours of plants and related elements. Along with specially selected plants, the sensory garden will include elements such as wind chimes, wind socks, flags, and art.</p>

  <p>An existing concrete outbuilding will be renovated for a wood- work room, complete with tools to make wooden items for sale, and a potter’s wheel & clay to create art which is a proven therapeutic activity.</p>

  <p>The house is surrounded by hills and trees and boasts quiet, picturesque woodland walks which make it an ideal setting for rest and recuperation.</p>

  <p>Cefn Coed is in an ideal location as it is close to all amenities and on a bus route. The regional shopping centre is situated at the Heads of the Valleys retail park in Merthyr Tydfil and the traditional shops and market in the historic town centre. Merthyr Tydfil has a number of places to dine and wine bars for a social evening with friendly local people.</p> 

  <p>There are a number of historic and places of interest to visit and a range of leisure opportunities, community projects, and activities within the town centre and county borough.</p>

	<div class="cl"></div>
     <div class="fullwidth_divider"></div>
								
 </div>
</div>
<!-- __________________________________________________ Finish Content -->		

 </div>
</section>

<script type="text/javascript">
  /* Caritas gallery */

   var speed = 100;

    jQuery(".prev").click(function(e) {
      e.preventDefault();
        var now = jQuery(this).parent().next("ul.gallery").children(":visible"),
            last = jQuery(this).parent().next("ul.gallery").children(":last"),
            prev = now.prev();
            prev = prev.index() == -1 ? last : prev;
        now.fadeOut(speed, function() {prev.fadeIn(speed);});
    });

    jQuery(".next").click(function(e) {
      e.preventDefault();
        var now = jQuery(this).parent().next("ul.gallery").children(':visible'),
            first = jQuery(this).parent().next("ul.gallery").children(':first'),
            next = now.next();
            next = next.index() == -1 ? first : next;
        now.fadeOut(speed, function() {next.fadeIn(speed);});
    });
</script>

app/views/shared/_footer.html.erb
<footer id="footer">
 <div class="footer_inner">
  <span>Richard Lewis &copy; 2013 All rights reserved</span>
   <div class="fr">
	<ul id="footer_nav" class="footer_nav">
	  <li><%= link_to 'Home', root_path %></li>
	  <li><%= link_to 'About Us', about_path %></li>
	  <li><%= link_to 'Contact Us', contact_path %></li>
	</ul>
   </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<a href="#" id="slide_top"></a>
 <header id="header">
  <div class="header_inner">
   <div class="social_block">
	<ul>
	 <li>
	  <a href="https://twitter.com/SupportedLMT" target="_blank">
	  	<%= image_tag("/assets/socialicons/twitter.png") %>
	  </a>
	 </li>
    
    <li>
	 <a href="https://www.facebook.com/supportedlivingmerthyr" target="_blank">
	  <%= image_tag("/assets/socialicons/facebook.png") %>
	 </a>
	</li>
   </ul>
	<a class="social_toggle" href="#"><span></span></a>
   </div>
   <%= link_to image_tag('/assets/logo.png', :size => '293x55'), root_path, :class => 'logo' %>
   <div class="captionHolder">
   	<span class="caption">Provider of Independent Living & Outreach Services in Merthyr Tydfil.....The Evolution of a Unique, Social Enterprise Project</span>
   </div>
    
	<a class="resp_navigation" href="javascript:void(0);"><span></span></a>
	<div class="cl"></div>

					
	<nav>
	 <ul id="navigation">
	  <li>
	  	<%= link_to root_path do %>
	  	 <span>Home</span>
	  	<% end %>
	  </li>
	  
	  <li class="drop">
	  	<%= link_to about_path do %>
	  	 <span>About Us</span>
	  	<% end %>
	  </li>
								
	 <li class="drop" id="projects">
	 	<a href="#">
	 	 <span>Our Projects</span>
	 	</a>
	  	<ul>
	  	  <li>
	  	  	<%= link_to our_projects_caritas_path do %>
		     <span>Edith Mary House</span>
		    <% end %>
	  	  </li>
	  </ul>
	 
	 <li>
	 	<%= link_to contact_path do %>
	 	 <span>Contact Us</span>
	    <% end %>
	 </li>
	</ul>
	<div class="cl"></div>
   </nav>
	<div class="cl"></div>
  </div>
</header>

<script type="text/javascript" charset="utf-8">
//<![CDATA[
jQuery(function() {

  jQuery('#navigation li').each(function() {
    var href = jQuery(this).find('a').attr('href');
    if (href === window.location.pathname) {
      jQuery(this).addClass('current_page_item');
    }
  });

});  
//]]>
</script>